PKG_NAME := pypi-hypothesis
URL = https://files.pythonhosted.org/packages/13/4a/c1fc2d7143bb3b5bf826f45ce2e0c9bf17ef8af044362e2d8dbda2d01190/hypothesis-6.108.9.tar.gz
ARCHIVES = 

include ../common/Makefile.common
